[character]
success_symbol = "[\\( ^o^\\) <](green)"
error_symbol = "[\\(;^o^\\) <](bright-blue)"

[directory]
truncate_to_repo = false

[git_status]
conflicted = "ðŸ’£"
modified = "ðŸ“"
untracked = "ðŸ¤·"
stashed = "ðŸ“¦"
prefix = "git[ "
suffix = " ]"
disabled = true

[git_branch]
symbol = "ðŸŒ± "
style = "bold #8cc16d"

[nodejs]
disabled = true

[package]
disabled = true
