[character]
symbol = "( ^o^) <"
error_symbol = "(;^o^) <"
use_symbol_for_status = true
style_success = "green"
style_failure = "blue"

[directory]
truncate_to_repo = false

[git_status]
conflicted = "ğŸ’£"
modified = "ğŸ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
prefix = "git[ "
suffix = " ]"
disabled = true

[git_branch]
symbol = "ğŸŒ± "
style = "bold #8cc16d"

[nodejs]
disabled = true

[package]
disabled = true
