[character]
symbol = "( ^o^) <"
error_symbol = "(;^o^) <"
style_success = "green"
style_failure = "blue"

[directory]
truncate_to_repo = false

[git_status]
modified = "ğŸ“ "
untracked = "ğŸ¤· "
stashed = "ğŸ“¦ "
prefix = "git[ "
suffix = "]"

[git_branch]
symbol = "ğŸŒ± "

[nodejs]
disabled = true

[package]
disabled = true
